import smartTvImage from "./images/smart-tv.png";
import smartTvImage2 from "./images/smart-tv-2.png";
import smartTvImage3 from "./images/smart-tv-3.png";
import smartTvImage4 from "./images/smart-tv-4.png";
import smartTvImage5 from "./images/smart-tv-5.png";

import manAvatar from "./images/placeholder-man.png";
import womanAvatar from "./images/placeholder-woman.png";

const itemTitle =
  "Lorem ipsum dolor sit amet consectetur adipisicing umpedit iste voluptate" +
  " nulla reprehenderit tempore cum consequatur quis ut quidem.";

const tlt =
  "Lorem ipsum dolor sit amet consectetur adipisicing, elit. " +
  "Repudiandae vero, enim deserunt nemo delectus pariatur soluta illo dolores nihil non.";

export const Items = [
  {
    id: "ART-025493",
    image: [
      smartTvImage,
      smartTvImage2,
      smartTvImage3,
      smartTvImage4,
      smartTvImage5,
    ],
    title: itemTitle,
    retailPrice: 1850,
    offerPrice: 1700,
    status: "Nuevo",
    views: 10,
    department: "Electrodomesticos",
    isInCart: false,
    addingDate: "2021-05-12",
    quality: 4.8,
    stock: 12,
    comments: [
      {
        id: "CMT-025489",
        userName: "John Doe",
        image: manAvatar,
        date: new Date(2021, 6, 3),
        text: tlt + ". " + tlt,
      },
      {
        id: "CMT-025964",
        userName: "Sarah Doe",
        image: womanAvatar,
        date: new Date(2021, 6, 4),
        text: tlt + ". " + tlt,
      },
    ],
    subItem: [
      {
        retailPrice: 1850,
        offerPrice: 1700,
        color: "black",
        capacity: "2GB",
        size: '17"',
        stock: 5,
      },
      {
        retailPrice: 1850,
        offerPrice: 1700,
        color: "gray",
        capacity: "2GB",
        size: '17"',
        stock: 10,
      },
      {
        retailPrice: 2350,
        offerPrice: 2140,
        color: "gray",
        capacity: "4GB",
        size: '32"',
        stock: 6,
      },
      {
        retailPrice: 1980,
        offerPrice: 1910,
        color: "purple",
        capacity: "4GB",
        size: '17"',
        stock: 4,
      },
      {
        retailPrice: 2320,
        offerPrice: 2290,
        color: "green",
        capacity: "6GB",
        size: '22"',
        stock: 4,
      },
    ],
  },
  {
    id: "ART-025381",
    image: [
      smartTvImage,
      smartTvImage2,
      smartTvImage3,
      smartTvImage4,
      smartTvImage5,
    ],
    title: itemTitle,
    retailPrice: 1150,
    offerPrice: 0,
    status: "Nuevo",
    views: 2,
    department: "Electrodomesticos",
    isInCart: false,
    addingDate: "2021-05-12",
    quality: 3.5,
    stock: 9,

    comments: [
      {
        id: "CMT-025974",
        userName: "John Doe",
        image: manAvatar,
        date: new Date(2021, 6, 3),
        text: tlt + ". " + tlt,
      },
      {
        id: "CMT-025315",
        userName: "Sarah Doe",
        image: womanAvatar,
        date: new Date(2021, 6, 4),
        text: tlt + ". " + tlt,
      },
    ],
    subItem: [
      {
        retailPrice: 1850,
        offerPrice: 1700,
        color: "black",
        capacity: "2GB",
        size: '17"',
        stock: 7,
      },
      {
        retailPrice: 1850,
        offerPrice: 1700,
        color: "gray",
        capacity: "2GB",
        size: '17"',
        stock: 8,
      },
      {
        retailPrice: 2350,
        offerPrice: 2140,
        color: "gray",
        capacity: "4GB",
        size: '32"',
        stock: 2,
      },
      {
        retailPrice: 1980,
        offerPrice: 1910,
        color: "purple",
        capacity: "4GB",
        size: '17"',
        stock: 1,
      },
      {
        retailPrice: 2320,
        offerPrice: 2290,
        color: "green",
        capacity: "6GB",
        size: '22"',
        stock: 4,
      },
    ],
  },
  {
    id: "ART-025136",
    image: [
      smartTvImage,
      smartTvImage2,
      smartTvImage3,
      smartTvImage4,
      smartTvImage5,
    ],
    title: itemTitle,
    retailPrice: 900,
    offerPrice: 845,
    status: "Usado",
    views: 60,
    department: "Electrodomesticos",
    isInCart: false,
    addingDate: "2021-05-12",
    quality: 0.8,
    stock: 13,
    comments: [
      {
        id: "CMT-025468",
        userName: "John Doe",
        image: manAvatar,
        date: new Date(2021, 6, 3),
        text: tlt + ". " + tlt,
      },
      {
        id: "CMT-025558",
        userName: "Sarah Doe",
        image: womanAvatar,
        date: new Date(2021, 6, 4),
        text: tlt + ". " + tlt,
      },
    ],
    subItem: [
      {
        retailPrice: 1850,
        offerPrice: 1700,
        color: "black",
        capacity: "2GB",
        size: '17"',
        stock: 5,
      },
      {
        retailPrice: 1850,
        offerPrice: 1700,
        color: "gray",
        capacity: "2GB",
        size: '17"',
        stock: 10,
      },
      {
        retailPrice: 2350,
        offerPrice: 2140,
        color: "gray",
        capacity: "4GB",
        size: '32"',
        stock: 3,
      },
      {
        retailPrice: 1980,
        offerPrice: 1910,
        color: "purple",
        capacity: "4GB",
        size: '17"',
        stock: 4,
      },
      {
        retailPrice: 2320,
        offerPrice: 2290,
        color: "green",
        capacity: "6GB",
        size: '22"',
        stock: 4,
      },
    ],
  },
  {
    id: "ART-025014",
    image: [
      smartTvImage,
      smartTvImage2,
      smartTvImage3,
      smartTvImage4,
      smartTvImage5,
    ],
    title: itemTitle,
    retailPrice: 800,
    offerPrice: 600,
    status: "Nuevo",
    views: 4,
    department: "Electrodomesticos",
    isInCart: false,
    addingDate: "2021-05-12",
    quality: 4.6,
    stock: 10,
    comments: [
      {
        id: "CMT-025779",
        userName: "John Doe",
        image: manAvatar,
        date: new Date(2021, 6, 3),
        text: tlt + ". " + tlt,
      },
      {
        id: "CMT-025697",
        userName: "Sarah Doe",
        image: womanAvatar,
        date: new Date(2021, 6, 4),
        text: tlt + ". " + tlt,
      },
    ],
    subItem: [
      {
        retailPrice: 1850,
        offerPrice: 1700,
        color: "black",
        capacity: "2GB",
        size: '17"',
        stock: 5,
      },
      {
        retailPrice: 1850,
        offerPrice: 1700,
        color: "gray",
        capacity: "2GB",
        size: '17"',
        stock: 10,
      },
      {
        retailPrice: 2350,
        offerPrice: 2140,
        color: "gray",
        capacity: "4GB",
        size: '32"',
        stock: 3,
      },
      {
        retailPrice: 1980,
        offerPrice: 1910,
        color: "purple",
        capacity: "4GB",
        size: '17"',
        stock: 4,
      },
      {
        retailPrice: 2320,
        offerPrice: 2290,
        color: "green",
        capacity: "6GB",
        size: '22"',
        stock: 4,
      },
    ],
  },
  {
    id: "ART-025489",
    image: [
      smartTvImage,
      smartTvImage2,
      smartTvImage3,
      smartTvImage4,
      smartTvImage5,
    ],
    title: itemTitle,
    retailPrice: 570,
    offerPrice: 0,
    status: "Usado",
    views: 15,
    department: "Electrodomesticos",
    isInCart: false,
    addingDate: "2021-05-12",
    quality: 3.8,
    stock: 7,

    comments: [
      {
        id: "CMT-025741",
        userName: "John Doe",
        image: manAvatar,
        date: new Date(2021, 6, 3),
        text: tlt + ". " + tlt,
      },
      {
        id: "CMT-025048",
        userName: "Sarah Doe",
        image: womanAvatar,
        date: new Date(2021, 6, 4),
        text: tlt + ". " + tlt,
      },
    ],
    subItem: [
      {
        retailPrice: 1850,
        offerPrice: 1700,
        color: "black",
        capacity: "2GB",
        size: '17"',
        stock: 5,
      },
      {
        retailPrice: 1850,
        offerPrice: 1700,
        color: "gray",
        capacity: "2GB",
        size: '17"',
        stock: 10,
      },
      {
        retailPrice: 2350,
        offerPrice: 2140,
        color: "gray",
        capacity: "4GB",
        size: '32"',
        stock: 3,
      },
      {
        retailPrice: 1980,
        offerPrice: 1910,
        color: "purple",
        capacity: "4GB",
        size: '17"',
        stock: 4,
      },
      {
        retailPrice: 2320,
        offerPrice: 2290,
        color: "green",
        capacity: "6GB",
        size: '22"',
        stock: 4,
      },
    ],
  },
  {
    id: "ART-025322",
    image: [
      smartTvImage,
      smartTvImage2,
      smartTvImage3,
      smartTvImage4,
      smartTvImage5,
    ],
    title: itemTitle,
    retailPrice: 1400,
    offerPrice: 1200,
    status: "Usado",
    views: 36,
    department: "Electrodomesticos",
    isInCart: false,
    addingDate: "2021-05-12",
    quality: 4.2,
    stock: 18,
    comments: [
      {
        id: "CMT-025612",
        userName: "John Doe",
        image: manAvatar,
        date: new Date(2021, 6, 3),
        text: tlt + ". " + tlt,
      },
      {
        id: "CMT-025917",
        userName: "Sarah Doe",
        image: womanAvatar,
        date: new Date(2021, 6, 4),
        text: tlt + ". " + tlt,
      },
    ],
    subItem: [
      {
        retailPrice: 1850,
        offerPrice: 1700,
        color: "black",
        capacity: "2GB",
        size: '17"',
        stock: 5,
      },
      {
        retailPrice: 1850,
        offerPrice: 1700,
        color: "gray",
        capacity: "2GB",
        size: '17"',
        stock: 10,
      },
      {
        retailPrice: 2350,
        offerPrice: 2140,
        color: "gray",
        capacity: "4GB",
        size: '32"',
        stock: 3,
      },
      {
        retailPrice: 1980,
        offerPrice: 1910,
        color: "purple",
        capacity: "4GB",
        size: '17"',
        stock: 4,
      },
      {
        retailPrice: 2320,
        offerPrice: 2290,
        color: "green",
        capacity: "6GB",
        size: '22"',
        stock: 4,
      },
    ],
  },
  {
    id: "ART-025189",
    image: [
      smartTvImage,
      smartTvImage2,
      smartTvImage3,
      smartTvImage4,
      smartTvImage5,
    ],
    title: itemTitle,
    retailPrice: 1600,
    offerPrice: 1400,
    status: "Reparado",
    views: 3,
    department: "Electrodomesticos",
    isInCart: false,
    addingDate: "2021-05-12",
    quality: 2.9,
    stock: 5,

    comments: [
      {
        id: "CMT-025110",
        userName: "John Doe",
        image: manAvatar,
        date: new Date(2021, 6, 3),
        text: tlt + ". " + tlt,
      },
      {
        id: "CMT-025003",
        userName: "Sarah Doe",
        image: womanAvatar,
        date: new Date(2021, 6, 4),
        text: tlt + ". " + tlt,
      },
    ],
    subItem: [
      {
        retailPrice: 1850,
        offerPrice: 1700,
        color: "black",
        capacity: "2GB",
        size: '17"',
        stock: 5,
      },
      {
        retailPrice: 1850,
        offerPrice: 1700,
        color: "gray",
        capacity: "2GB",
        size: '17"',
        stock: 10,
      },
      {
        retailPrice: 2350,
        offerPrice: 2140,
        color: "gray",
        capacity: "4GB",
        size: '32"',
        stock: 3,
      },
      {
        retailPrice: 1980,
        offerPrice: 1910,
        color: "purple",
        capacity: "4GB",
        size: '17"',
        stock: 4,
      },
      {
        retailPrice: 2320,
        offerPrice: 2290,
        color: "green",
        capacity: "6GB",
        size: '22"',
        stock: 4,
      },
    ],
  },
  {
    id: "ART-025777",
    image: [
      smartTvImage,
      smartTvImage2,
      smartTvImage3,
      smartTvImage4,
      smartTvImage5,
    ],
    title: itemTitle,
    retailPrice: 600,
    offerPrice: 0,
    status: "Nuevo",
    views: 39,
    department: "Electrodomesticos",
    isInCart: false,
    addingDate: "2021-05-12",
    quality: 1.2,
    stock: 9,

    comments: [
      {
        id: "CMT-025995",
        userName: "John Doe",
        image: manAvatar,
        date: new Date(2021, 6, 3),
        text: tlt + ". " + tlt,
      },
      {
        id: "CMT-025031",
        userName: "Sarah Doe",
        image: womanAvatar,
        date: new Date(2021, 6, 4),
        text: tlt + ". " + tlt,
      },
    ],
    subItem: [
      {
        retailPrice: 1850,
        offerPrice: 1700,
        color: "black",
        capacity: "2GB",
        size: '17"',
        stock: 5,
      },
      {
        retailPrice: 1850,
        offerPrice: 1700,
        color: "gray",
        capacity: "2GB",
        size: '17"',
        stock: 10,
      },
      {
        retailPrice: 2350,
        offerPrice: 2140,
        color: "gray",
        capacity: "4GB",
        size: '32"',
        stock: 3,
      },
      {
        retailPrice: 1980,
        offerPrice: 1910,
        color: "purple",
        capacity: "4GB",
        size: '17"',
        stock: 4,
      },
      {
        retailPrice: 2320,
        offerPrice: 2290,
        color: "green",
        capacity: "6GB",
        size: '22"',
        stock: 4,
      },
    ],
  },
  {
    id: "ART-025610",
    image: [
      smartTvImage,
      smartTvImage2,
      smartTvImage3,
      smartTvImage4,
      smartTvImage5,
    ],
    title: itemTitle,
    retailPrice: 425,
    offerPrice: 0,
    status: "Usado",
    views: 17,
    department: "Electrodomesticos",
    isInCart: false,
    addingDate: "2021-05-12",
    quality: 4.9,
    stock: 13,
    comments: [
      {
        id: "CMT-025711",
        userName: "John Doe",
        image: manAvatar,
        date: new Date(2021, 6, 3),
        text: tlt + ". " + tlt,
      },
      {
        id: "CMT-025229",
        userName: "Sarah Doe",
        image: womanAvatar,
        date: new Date(2021, 6, 4),
        text: tlt + ". " + tlt,
      },
    ],
    subItem: [
      {
        retailPrice: 1850,
        offerPrice: 1700,
        color: "black",
        capacity: "2GB",
        size: '17"',
        stock: 5,
      },
      {
        retailPrice: 1850,
        offerPrice: 1700,
        color: "gray",
        capacity: "2GB",
        size: '17"',
        stock: 10,
      },
      {
        retailPrice: 2350,
        offerPrice: 2140,
        color: "gray",
        capacity: "4GB",
        size: '32"',
        stock: 3,
      },
      {
        retailPrice: 1980,
        offerPrice: 1910,
        color: "purple",
        capacity: "4GB",
        size: '17"',
        stock: 4,
      },
      {
        retailPrice: 2320,
        offerPrice: 2290,
        color: "green",
        capacity: "6GB",
        size: '22"',
        stock: 4,
      },
    ],
  },
];

export const Departments = [
  "Ropa para mujer",
  "Ropa para hombre",
  "Carteras y Relojes",
  "Calzados",
  "Electrodomésticos",
  "Teléfonos y Comunicaciones",
  "Informática y Oficina",
  "Componentes Electrónicos",
  "Entretenimiento y Video juegos",
  "Herramientas del Hogar",
  "Automotriz",
];

export const Order = [
  {
    id: "ORD-025984",
    orderDate: "2021-05-07",
    deliveredDate: "2021-05-08",
    orderStatus: "received",
    shippingCost: 150,
    total: 5155.91,
    client: {
      name: "John Doe",
      email: "johndoe0102@gmail.com",
      phone: "809-111-0000",
      address:
        "Casa 8, Francisco Henriquez y Carvajal, Brisas del Este, Santo Domingo Este",
      indications:
        "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusantium quaerat " +
        "suscipit esse voluptate! Odit quia id possimus.",
    },
    items: [
      {
        image: smartTvImage,
        title: tlt,
        amount: 2,
        price: 1527.33,
        condition: "none",
      },
      {
        image: smartTvImage2,
        title: tlt,
        amount: 1,
        price: 2101.25,
        condition: "none",
      },
    ],
  },
  {
    id: "ORD-025741",
    orderDate: "2021-05-14",
    deliveredDate: "2021-05-16",
    orderStatus: "onitsway",
    shippingCost: 150,
    total: 1350,
    client: {
      name: "John Doe",
      email: "johndoe0102@gmail.com",
      phone: "809-111-0000",
      address:
        "Casa 8, Francisco Henriquez y Carvajal, Brisas del Este, Santo Domingo Este",
      indications:
        "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusantium quaerat " +
        "suscipit esse voluptate! Odit quia id possimus.",
    },
    items: [
      {
        image: smartTvImage3,
        title: tlt,
        amount: 1,
        price: 1200,
        condition: "none",
      },
    ],
  },
];
